### PR TITLE
Bump ts to 2.1

### PR DESCRIPTION
**Pull request by sixinli**
fixed a few more things after https://github.com/palantir/eclipse-typescript/pull/337

@Rouche @mzmaryzhuang

### CODE REVIEW

**Comment by Rouche** [comment]
Cool @sixinli 
Did you merged my fork? If no, this commit end up almost identical lol.

I had a few more fixes, #337 changed the updateTypeScript.sh case of directory, i did the same because the directory in the first line (```cd ..\TypeScript```) is cased.

I also wanted to bump Tycko to latest version (0.26) so the reference in the project can be JavaSE_1.8. 

And of course double verify compiler options.

**Comment by sixinli** [comment]
ah cool, i can update the `Typescript` casing, do you mind opening a separate PR for updating Tycko @Rouche ? I will update the docs PR too

**Comment by Rouche** [comment]
This also fixes #331

**Comment by Rouche** [comment]
@sixinli Hi, did you get my mail about the casing? (Type**S**cript) is the name of the Git repository by default. (https://github.com/Microsoft/TypeScript)

Also, I just updated Tycho to 0.26.0 and changed the Eclipse repository to use Mars instead of Kepler.

Problem is it will have conflicts with your commit. I will have to wait for yours to be merged because i need to remove .qualifier from versions in pom.xml due to changes in Tycho validations.

**Comment by sixinli** [comment]
oops my bad on misreading the casing, changing it now

**Comment by sixinli** [comment]
@Rouche looks good? will merge if so :)

**Comment by Rouche** [comment]
@sixinli Yep! 👍

**Comment by sixinli** [comment]
@Rouche the publish task has some problem, we are fixing it atm. You might need to build it locally for now :( sorry

**Comment by Rouche** [comment]
Yeah no problem.

Will re-fork and PR the Tycho update later this week.

**Comment by david-bouyssie** [comment]
BUILD SUCCESS only if I use the following command line:
```mvn -DforceContextQualifier=true package```

Otherwise I get the error:
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-packaging-plugin:0.18.1:build-qualifier (default-build-qualifier) on project com.palantir.typescript: Execution default-build-qualifier of goal org.eclipse.tycho:tycho-packaging-plugin:0.18.1:build-qualifier failed: One of setGitDir or setWorkTree must be called.

**Comment by Rouche** [comment]
Maven version maybe? Runnin in parent dir? Option in settings.xml? Just ideas, hard to tell when travis build is ok and mine too.

**Comment by david-bouyssie** [comment]
My maven version is 3.3.3
However my "settings.xml" file is configured to target an artifactory, so it may explain the problem.

**Pull request merged**
