### PR TITLE
Fixes #313

### LINKED ISSUE #313: Matching bracket color
Hi,

I just want to know what color / system variable the TypeScript editor "matching bracket" color is using. I really want to change it because i use black theme.

I tryed everything.

General->Editors->Text Editors->Annotations->Matching tags : Not working
General->Editors->Structured Text Editor->Matching brackets highlight : Not working
Javascript->Editor->Matching brackets highlight : Not working
Java->Editor->Matching brackets highlight : Not working (of course)

Theres also another one defined in plugin.xml of org.eclipse.jdt.ui
I overriden this color too. And yeah not working either.
```
<colorDefinition
    id="org.eclipse.jdt.ui.matchingBracketsColor"
    isEditable="false"
    label="%Dummy.label"
    value="240,240,240">
</colorDefinition>
```

Edit:
I saw this line in IPreferenceConstants, should this line be changed to "org.eclipse.jdt.ui.matchingBracketsColor" ? It my screenshot this does not seem to be 128,128,128.
```
String EDITOR_MATCHING_BRACKETS_COLOR = "editor.matchingBracketsColor";
```
```
        store.setDefault(IPreferenceConstants.EDITOR_MATCHING_BRACKETS_COLOR, "128,128,128");
```

Thanks

### PR DESCRIPTION
**Pull request by Rouche**
Matching bracket color now uses JDT preference color. Wich can be
changed in Windows->Preferences->Java->Editor->Matching Bracket
Highlight

I could not find the Javascript exposed preference store.

### CODE REVIEW

**Comment by derekcicerone** [comment]
Cool, thanks!

**Comment by derekcicerone** [comment]
oh wait, this takes a dependency upon Java, oh sorry, that's probably not a good idea, sorry

**Comment by derekcicerone** [comment]
Sorry, is there a way to do this without taking a dependency upon Java? I don't think its good to couple the TypeScript plugin with Java - that could break for folks that don't have Java installed.

**Comment by Rouche** [comment]
Sadly, I did not find the Javascript's plugin exposed store.

The best would be using the "StructuredEditor" Store and property name for Matching bracket. Hoping they do expose it....
I will search for it as soon as i can. Sorry for the JDT dep.

If its not exposed, the only option we have to make this one configurable without a TypeScript option page is going Introspection like this, not sure you will like :P
```
try {
Class.forName("org.eclipse.jdt.ui.PreferenceConstants")
// get store.
}
```

**Comment by derekcicerone** [comment]
I don't think we'd want to depend upon JavaScript either - the TypeScript editor support is otherwise totally independent. The runtime check also seems kinda hacky. The color support in Eclipse seems somewhat half-baked to me to be honest. We got it working well with a color management plugin - perhaps it needs to be hooked into that? Sorry, been a while since I worked on the color theme support.

**Comment by Rouche** [comment]
*Sigh* i guess its a no go too.

Directly from : https://bugs.eclipse.org/bugs/show_bug.cgi?id=312211

**That preference page will only be there if you have the source editing plug-ins from WTP.**

**Comment by Rouche** [comment]
Well i just found one version without org.eclipse.wst.sse.ui dependency and its the C++ version.

If you want, implement it using this package in a try/catch at runtime. Its gonna benefit a lot of people and for others too bad, it will be the default.

Your call. As for the color management, i have no idea. 

Regards!

**Comment by derekcicerone** [comment]
Yeah, this is tricky - I'd like to hold off for a more correct solution.

**Pull request merged**
