### PR TITLE
Updated typescript from 1.8 to 2.1.

### PR DESCRIPTION
**Pull request by mzmaryzhuang**

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/eclipse-typescript](https://github.com/palantir/eclipse-typescript), @mzmaryzhuang! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by mzmaryzhuang** [comment]
Looks like LanguageService is missing getSourceFile now, not sure how to fix this. Leaving this here in case someone else can help figure it out.

**Comment by Rouche** [comment]
Seems like the ```getSourceFile``` can be accessed with ```languageService.getProgram().getSourceFile```

I am testing if everything is ok.

**Comment by sixinli** [comment]
it will be great to get it working with ts2.x, let me know how i can help @Rouche

**Comment by sixinli** [comment]
closed by #339

**Pull request closed without merging**
