### PR TITLE
fix for bug #267

### PR DESCRIPTION
**Pull request by StefanBrands**
Fix for markers not showing up when other projects reference the
project.

### CODE REVIEW

**Comment by derekcicerone** [comment]
Great find, thanks!

**Comment by StefanBrands** [comment]
No problem :)

**Comment by mttcr** [comment]
When will this fix be available at http://eclipse-update.palantir.com/eclipse-typescript-develop/ (or http://eclipse-update.palantir.com/eclipse-typescript/) with the latest Typescript 1.6 code ?

**Comment by derekcicerone** [comment]
It should already be available if you update.

**Pull request merged**
